### ISSUE TITLE
Stopped working with actual-server V24+

### ISSUE THREAD

**Issue by ChevySSinSD** [lancepick/actual-simplefin-sync#3]
The following error is thrown after upgrading to actual server v24.1.0:

```
Initializing Actual Budget...
Database is out of sync with migrations: {
  appliedIds: [
    1548957970627, 1550601598648,
    1555786194328, 1561751833510,
    1567699552727, 1582384163573,
    1597756566448, 1608652596043,
    1608652596044, 1612625548236,
    1614782639336, 1615745967948,
    1616167010796, 1618975177358,
    1632571489012, 1679728867040,
    1681115033845, 1682974838138,
    1685007876842, 1686139660866,
    1688749527273, 1688841238000,
    1691233396000, 1694438752000,
    1697046240000, 1704572023730,
    1704572023731, 1707267033000
  ],
  available: [
    '1548957970627_remove-db-version.sql',
    '1550601598648_payees.sql',
    '1555786194328_remove_category_group_unique.sql',
    '1561751833510_indexes.sql',
    '1567699552727_budget.sql',
    '1582384163573_cleared.sql',
    '1597756566448_rules.sql',
    '1608652596043_parent_field.sql',
    '1608652596044_trans_views.sql',
    '1612625548236_optimize.sql',
    '1614782639336_trans_views2.sql',
    '1615745967948_meta.sql',
    '1616167010796_accounts_order.sql',
    '1618975177358_schedules.sql',
    '1632571489012_remove_cache.js',
    '1679728867040_rules_conditions.sql',
    '1681115033845_add_schedule_name.sql',
    '1682974838138_remove_payee_rules.sql',
    '1685007876842_add_category_hidden.sql',
    '1686139660866_remove_account_type.sql',
    '1688749527273_transaction_filters.sql',
    '1688841238000_add_account_type.sql',
    '1691233396000_add_schedule_next_date_tombstone.sql',
    '1694438752000_add_goal_targets.sql',
    '1697046240000_add_reconciled.sql'
  ]
}
Error updating Error: out-of-sync-migrations
    at checkDatabaseValidity (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44308:31)
    at Module.migrate (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44316:17)
    at async runMigrations (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:48024:17)
    at async updateVersion (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:48043:17)
    at async loadBudget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43914:21)
    at async handlers.load-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43744:27)
    at async handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43714:17)
    at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:34861:34)
TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47369:96)
    at /app/node_modules/@actual-app/api/dist/app/bundle.api.js:47281:38
    at onceFn (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:48220:35)
    at initialFullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47267:36)
    at handlers.sync-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43729:92)
    at handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43717:55)
    at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:34861:34)
[Exception] TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47369:96)
    at /app/node_modules/@actual-app/api/dist/app/bundle.api.js:47281:38
    at onceFn (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:48220:35)
    at initialFullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47267:36)
    at handlers.sync-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43729:92)
    at handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43717:55)
    at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:34861:34)
Full error details {
  message: "Cannot read properties of undefined (reading 'timestamp')",
  reason: undefined,
  meta: undefined
}
/app/node_modules/@actual-app/api/dist/app/bundle.api.js:34866
                        throw new Error((0, _shared_errors__WEBPACK_IMPORTED_MODULE_2__.getDownloadError)(result.error));
                              ^

Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (reason: undefined)
    at handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:34866:31)

Node.js v21.4.0
```

I can verify the sync still works on v23.12.1, but unfortunately, I can't roll back my database to older version.

**Comment by nathanWilson81** [comment]
I am also experiencing this issue

**Comment by nathanWilson81** [comment]
@ChevySSinSD v24.2.0 has an experimental feature to use SimpleFin directly within Actual. I set it up and it's working well for me. Something to look in to

**Comment by ChevySSinSD** [comment]
@nathanWilson81 Thanks, after a lot of trial and error, I have the experimental feature working!
